// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestSDKClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Container File class for files from the container
    /// </summary>
    public partial class ContainerFile
    {
        /// <summary>
        /// Initializes a new instance of the ContainerFile class.
        /// </summary>
        public ContainerFile() { }

        /// <summary>
        /// Initializes a new instance of the ContainerFile class.
        /// </summary>
        public ContainerFile(string name = default(string))
        {
            Name = name;
        }

        /// <summary>
        /// name of the file from a container
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
